language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=AccountBalance.xcworkspace
  - SCHEME=AccountBalance
  - SDK=macosx10.12
  - DESTINATION="arch=x86_64"
cache:
  - bundler
  - cocoapods
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod update
script: 
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty
